### PR TITLE
Fix playlist card layout info (Closes #156)

### LINKED ISSUE #156: display the information corresponding to the design layout on the playlist card
Current Result:

Image

Expected Result:

Image

- [x] - playlist's cover
- [x] - playlist's title
- [x] - playlist's description should be removed from the card
- [x] - the text "Made for <author name and surname or his username>". Text should be a link to the user's profile.
- [ ] - playlist's track's count and created date
> [!WARNING]
> specify '0 tracks' if tracksCount info is still missing in the PlaylistAttributes
- [x] - reaction buttons and number of likes

### PR DESCRIPTION
**Pull request by pashz7**
1. Changed props in component PlaylistCard in PlaylistsPage , MainPage 
2. Delete description 
3. Added a function that formats the AddedAt property according to the Figma design
4. Moved types of PlaylistCard to a separate file PlayListCardTypes  
5. add a button that navigate to the playlist ownerPage  

Property tracksCount info is still missing in the PlaylistAttributes, i have an idea how to solve this problem , but i think it will be better to fix it on backend
Now element Card is a Link maybe it is will be better to restrict the clickable area to the playlist image only to choose the current Playlist.  Maybe i am wrong
It would be great to discuss the PlaylistCard UI on the user’s page.

### CODE REVIEW

File: apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx [hunk 1]
```diff
@@ -8,41 +8,37 @@ import {
...
 import noCoverPlaceholder from '@/shared/assets/images/no-cover-placeholder.avif'
 import { Card, CurrentUserReaction, ReactionButtons, Typography } from '@/shared/components'
-
+import type {MouseEvent} from "react";
 import s from './PlaylistCard.module.css'
+import {Paths} from "@/shared/configs";
+import {formatCreatedDate} from "@/shared/utils/formatCreatedDate.ts";
+import type {PlaylistCardProps} from "@/shared/types";
 
-type PlaylistCardPropsBase = {
```
Comment (Svyat-1418) [inline apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx:14]: If you want to move the component props related types from the component .tsx file, it would be better to put them to a saparate file **_next to the componenent file_** (in this case I would do it in `playlist-card.types.ts`).

It's better to leave these types here, since them are used only for PlaylistCard component

File: apps/rtk-query/src/pages/UserPage/ui/UserTabs/MyLikedPlaylistsTab/MyLikedPlaylistsTab.tsx [hunk 2]
```diff
@@ -54,7 +54,9 @@ export const MyLikedPlaylistsTab = () => {
                 id={playlist.id}
                 title={playlist.attributes.title}
                 imageSrc={image?.url}
-                description={playlist.attributes.description}
+                userName={playlist.attributes.user.name}
```
Comment (Svyat-1418) [inline apps/rtk-query/src/pages/UserPage/ui/UserTabs/MyLikedPlaylistsTab/MyLikedPlaylistsTab.tsx:58]:
```
    userName={playlist.attributes.user.name}
    userId={playlist.attributes.user.id}
    addedAt={playlist.attributes.addedAt}
```

Screenshot_396

Figma design shows that it's correct to display this info on **My Liked Playlists** tab, so you can leave it as it is.
However I supose that it's strange behavior

File: apps/rtk-query/src/pages/UserPage/ui/UserTabs/PlaylistsTab/PlaylistsTab.tsx [hunk 3]
```diff
@@ -49,7 +49,9 @@ export const PlaylistsTab = () => {
                 id={playlist.id}
                 title={playlist.attributes.title}
                 imageSrc={image?.url}
-                description={playlist.attributes.description}
+                userName={playlist.attributes.user.name}
```
Comment (Svyat-1418) [inline apps/rtk-query/src/pages/UserPage/ui/UserTabs/PlaylistsTab/PlaylistsTab.tsx]: Screenshot_397

`userName`, `createdAt`, `<ReactionButtons />` are **_excessive_** if it's **My Playlists** tab according to the design

File: apps/rtk-query/src/shared/types/playlistCardTypes.ts [hunk 4]
```diff
@@ -0,0 +1,23 @@
+import {CurrentUserReaction} from "@/shared/components";
```
Comment (Svyat-1418) [inline apps/rtk-query/src/shared/types/playlistCardTypes.ts]: I have already leave the review comment about PlaylistCard props types that you place here

File: apps/rtk-query/src/shared/utils/formatCreatedDate.ts [hunk 5]
```diff
@@ -0,0 +1,14 @@
...
+    }
+    const date = new Date(addedAt.toString())
+    const now = new Date()
+    const differTime = now.getTime() - date.getTime()
+    const differDays = Math.floor(differTime / (1000 * 60 * 60 * 24))
+    if (differDays === 0) {
+        return 'today'
+    }
+
+    return `${differDays} ${differDays === 1 ? 'day' : 'days'} ago`
```
Comment (Svyat-1418) [inline apps/rtk-query/src/shared/utils/formatCreatedDate.ts]: You should move static text to the translation instead of hardcode.

There's also text overflowing 

Screenshot_394

It should be handled, for example with `text-overflow: ellipses;` or infinite line animation on hover or more... button whose behavior also can be different

It would be better to display created date in DD/MM/YYYY format or with powerfull and easyweighting library? for example date-fns

**Comment by Svyat-1418** [comment]
@pashz7 
As far as number of tracks is concerned, it is already task for backend.

You said that have some proposals about this

**Review by pashz7 — COMMENTED** [review]
123

File: apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx [hunk 6]
```diff
@@ -58,9 +54,25 @@ export const PlaylistCard = ({
         </Typography>
         {actions}
       </div>
-      <Typography variant="body3" className={s.description}>
-        {description}
-      </Typography>
+
```
Comment (KirillDolzhenkov) [inline apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx]: Why did you remove the props description? I'm a little out of context, but is this component not reused anywhere else? Does it look the same everywhere? It looks like it could be passed from the outside as a slot. Maybe I'm wrong.

**Comment by pashz7** [comment]
@Svyat-1418 
Fixed UI on UserPage/Playlists according Figma 
Added navigation to the playlist page when the image is clicked.
Added  properties to JSON object for translating the playlist creation date.
Fixed function that displays the playlist creation date depending on its creation date.

**Review by Svyat-1418 — CHANGES_REQUESTED** [review]

**Review by Svyat-1418 — CHANGES_REQUESTED** [review]
@pashz7 
Rename your files with util functions from `camelCase` approach to `kebab-case`approach according to the **Naming** section from `README.md`.

Before perfoming this, update your local `develop` and then merge `develop` into your branch

File: apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx [hunk 7]
```diff
@@ -1,77 +1,127 @@
...
+                                 title,
+                                 imageSrc = noCoverPlaceholder,
+                                 id,
+                                 isShowReactionButtons,
+                                 actions,
+                                 userName,
+                                 userId,
+                                 addedAt,
+                                 isShowCurrentUser = true,
+                                 isShowCreatedDate = true,
```
Comment (Svyat-1418) [inline apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx]: - [x] - `isShowCurrentUser ` should be renamed to `shouldShowOwnerName`
- [x] - `isShowCreatedDate ` should be renamed to `shouldShowCreatedDate` 
- [x] - it's better to set default values of the renamed props above to `false`
- [x] - where owner name and/or Created date need to be displayed just pass to PlayllistCard only these props, for example `<PlayllistCard shouldShowCreatedDate  />`. It's the same as `<PlayllistCard shouldShowCreatedDate="true"  />`.

File: apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx [hunk 8]
```diff
@@ -1,77 +1,127 @@
...
+    }
+
+    return (
+        <Card
+            className={clsx(s.card, isShowReactionButtons && s.withReactionButtons)}>
+            <Link
+                to={`/playlists/${id}`}
+                className={s.imageLink}
+                aria-label={`Open playlist ${title}`}
+            >
```
Comment (Svyat-1418) [inline apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx]: - [x] - `Paths` constant object shold be used here instead of hardcode.
- [x] - `aria-label` value needs to be moved to the translations

File: apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx [hunk 9]
```diff
@@ -1,77 +1,127 @@
...
-      {/*  'reaction' in props — Type guard for correct type checking */}
-      {isShowReactionButtons && 'reaction' in props && (
+            <div className={s.details}>
+                {isShowCurrentUser &&
+                    <div className={s.madeFor}>
+                        <Typography variant="body2" as="span">Made for </Typography>
+                        <Link
+                            to={`/users/${userId}`}
+                            className={s.userLink}
+                            onClick={handleUserNameClick}
```
Comment (Svyat-1418) [inline apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx]: `to={`/users/${userId}`}` is excessive here: `handleUserNameClick` performs programming navigation

**Comment by pashz7** [comment]
@Svyat-1418 
fix naming of utils function according to kebab-case
and add reaction buttons in Tab LIkedPlaylists according to Figma

File: apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx [hunk 10]
```diff
@@ -1,77 +1,127 @@
...
-      </div>
-      <Typography variant="body3" className={s.description}>
-        {description}
-      </Typography>
-      {/*  'reaction' in props — Type guard for correct type checking */}
-      {isShowReactionButtons && 'reaction' in props && (
+            <div className={s.details}>
+                {isShowCurrentUser &&
+                    <div className={s.madeFor}>
+                        <Typography variant="body2" as="span">Made for </Typography>
```
Comment (Svyat-1418) [inline apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx]: add this text to the translations

File: apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx [hunk 11]
```diff
@@ -1,77 +1,127 @@
...
+                            onClick={handleUserNameClick}
+                        >
+                            {userName}
+                        </Link>
+                    </div>
+                }
+
+                <div className={s.detailsRow}>
+                    <Typography variant="body2" className={s.tracks}>
+                        0 tracks
```
Comment (Svyat-1418) [inline apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx]: `tracksCount` will be returned from the backend later, but `tracks` text needs to be taken from the translations.

Leave `TODO: ` for the `tracksCount`

**Review by Svyat-1418 — CHANGES_REQUESTED** [review]

**Comment by pashz7** [comment]
@Svyat-1418 
The suggested changes have been implemented. Please review when you have a moment.

File: apps/rtk-query/src/shared/translations/languages/ru.json [hunk 12]
```diff
@@ -134,5 +137,13 @@
     "no_options_found": "Ничего не найдено",
     "all_options_selected": "Выбраны все",
     "which_playlist": "В каком плейлисте находится трек?"
+  },
+  "playlist": {
+    "tracks_count_zero": "{{count}} треков",
+    "tracks_count_one": "{{count}} трек",
+    "tracks_count_two": "{{count}} трека",
+    "tracks_count_few": "{{count}} трека",
+    "tracks_count_many": "{{count}} треков",
```
Comment (Svyat-1418) [inline apps/rtk-query/src/shared/translations/languages/ru.json]: @pashz7  `tracks_count_two`, `tracks_count_many` may be excessive in this case.
Clarify me please your decision. It's quite possible that I'm mistaken.
Also you missed `made_for` for russian locale

File: apps/rtk-query/src/shared/translations/languages/en.json [hunk 13]
```diff
@@ -131,5 +134,10 @@
     "monthAgo": "{{addedAt}} month ago",
     "monthsAgo": "{{addedAt}} months ago",
     "created": "Created"
+  },
+  "playlist": {
+    "made_for": "Create for",
```
Comment (Svyat-1418) [inline apps/rtk-query/src/shared/translations/languages/en.json]: According to the Figma design, this should be `Made for` text

File: apps/rtk-query/src/shared/configs/paths.ts [hunk 14]
```diff
@@ -2,6 +2,7 @@ export const Paths = {
   Main: '/',
   Auth: '/sign-in',
   Playlists: '/playlists',
+  Playlist: '/playlists',
```
Comment (Svyat-1418) [inline apps/rtk-query/src/shared/configs/paths.ts]: I consider that the field `Playlist` is excessive because its value matches with the `Playlists` field value. It's better to use `to={`${Paths.Playlist}/${id}`}` in the `PlaylistCard` component

File: apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx [hunk 15]
```diff
@@ -21,8 +19,8 @@ type PlaylistCardPropsBase = {
     userName?: string
     userId?: string
     addedAt?: string
-    isShowCurrentUser?: boolean
-    isShowCreatedDate?: boolean
+    shouldShowOwnerName?: boolean
+    shouldShowCreateDate?: boolean
```
Comment (Svyat-1418) [inline apps/rtk-query/src/features/playlists/ui/PlaylistCard/PlaylistCard.tsx]: Here is a misspell: `shouldShowCreatedate` instead of `shouldShowCreateDate`. 

https://github.com/it-incubator/musicfun-react-all-stacks/pull/161#discussion_r2619622782

**Review by Svyat-1418 — CHANGES_REQUESTED** [review]
Setting your IDE for applying `eslint` and `prettier` preferances for the project. 
Some local setting of yours sets large gaps in some files

Image

File: apps/rtk-query/src/shared/translations/languages/ru.json (hunk 12 above)
Comment (pashz7) [reply apps/rtk-query/src/shared/translations/languages/ru.json]: I think you're right. I just included all possible cases. I agree that tracks_count_two is a redundant property. I added tracks_count_many for the correct translation into Russian (e.g., 1035 tracks). And I made the other property in case whole number values are needed for some statistics or something. And I created the other property just in case fractional values are needed for some kind of statistics (for example, something like an average number of tracks).

**Review by Svyat-1418 — APPROVED** [review]
Ok, It's acceptable
